var English = {
    "Emergency":"Emergency",
    "Mobile Version": "<i class='fas fa-mobile'></i>&nbsp;Mobile Version",
    "Askmebet Support": "Askmebet Support",
    "Username": "Username",
    "Password": "Password",
    "Sign in": "Sign in",
    "Contact your associate in case you forgot the password or unable to sign in": "Contact your associate in case you forgot the password or unable to sign in",
    "Close": "Close",
    "Guide": "<i class='fas fa-guide'></i>&nbsp;Guide",
    "Log Out": "<i class='fas fa-sign-out-alt'></i>&nbsp;Log Out",
    "Chat Bot": "Chat Bot",
    "Search User": "Search User",
    "Pretty Gaming": "Pretty Gaming",
    "Super Slot": "Super Slot",
    "Football": "Football",
    "Lotto": "Lotto",
    "Ambbet": "Ambbet",
    "missing 'Title' field": "Please enter 'Title'.",
    "missing 'Comment' field": "Please enter 'Comment'.",
    "missing 'Username' field": "Please enter 'Username'.",
    "missing 'Password' field": "Please enter 'Password'.",
    "missing 'Contact' field": "Please enter 'Contact'.",
    "missing 'Level' field": "Please select 'Level'.",
    "missing 'Company' field": "Please select 'Company'.",
    "missing 'Sub Agent' field": "Please select 'Sub Agent'.",
    "Save": "Save",
    "Add new account success.": "Add new account success.",
    "Data recording failed.": "Data recording failed. Please try again.",
    "Username is duplicate.": "Username is duplicate.",
    "Delete Account": "Delete Account",
    "Confirm delete this item ?": "Confirm delete this item ?",
    "OK": "OK",
    "Delete account success.": "Delete account success.",
    "Edit account success.": "Edit account success.",
    "missing 'Name' field": "Please enter 'Name'.",
    "missing 'Prefix' field": "Please enter 'Prefix'.",
    "Login failed.": "Login failed. Please try again.",
    "Logout failed.": "Logout failed. Please try again.",
    "Please select type.": "Please select type.",
    "Please select agent.": "Please select agent.",
    "Please enter bet ID.": "Please enter bet ID.",
    "Cancel bet ID success.": "Cancel bet ID success.",
    "Add new dashboard success.": "Add new dashboard success.",
    "missing 'Product' field": "Please enter 'Product'.",
    "missing 'Agent' field": "Please enter 'Agent'.",
    "missing 'Attach file' field": "Please select 'Attach file'.",
    "missing 'Category' field": "Please select 'Category'.",
    "missing 'Status' field": "Please select 'Status'.",
    "missing 'Start date' field": "Please enter 'Start date'.",
    "missing 'To date' field": "Please enter 'To date'.",
    "missing 'Type' field": "Please select 'Type'.",
    "missing 'Description' field": "Please enter 'Description'.",
    "Add new leave success.": "Add new leave success.",
    "Approve this leave success.": "Approve this leave success.",
    "Reject this leave success.": "Reject this leave success.",
    "missing 'Search' field": "Please enter 'Bet ID' or 'Username'.",
    "missing 'Old Password' field": "Please enter 'Old Password'",
    "missing 'New Password' field": "Please enter 'New Password'",
    "missing 'Confirm Password' field": "Please enter 'Confirm Password'",
    "New password doesn't match confirm password": "New password doesn't match confirm password",
    "Pickup dashboard success.": "Pickup dashboard success.",
    "Chat dashboard success.": "Chat dashboard success.",
    "Comment dashboard success.": "Comment dashboard success.",
    "Close dashboard success.": "Close dashboard success.",
    "Cancel dashboard success.": "Cancel dashboard success.",
    "Data recording failed. (Upload attach file)": "Data recording failed. Please try again. (Upload attach file)",
    "The old password doesn't match the current password.": "The old password doesn't match the current password.",
    "Password must be greater than 8 characters.": "Password must be greater than 8 characters.",
    "Field 'To Date' should be greater than 'Start Date'.": "Field 'To Date' should be greater than 'Start Date'.",
    "missing 'Website' field": "Please enter 'Website link'.",
    "missing 'Username' field": "Please enter 'Username'.",
    "missing 'Password' field": "Please enter 'Password'.",
    "missing 'Problem' field": "Please enter 'Problem'.",
    "missing 'Troubleshooting' field": "Please enter 'Troubleshooting'.",
    "missing 'Afterfirstfixed' field": "Please enter 'After first fixed'.",
    "Add new company success.": "Add new company success.",
    "Delete Company": "Delete Company",
    "Delete company success.": "Delete company success.",
    "Edit company success.": "Edit company success.",
    "Add new agent success.": "Add new agent success.",
    "Delete Agent": "Delete Agent",
    "Delete agent success.": "Delete agent success.",
    "Edit agent success.": "Edit agent success.",
    "Delete sub agent success.": "Delete sub agent success.",
    "Edit sub agent success.": "Edit sub agent success.",
    "Acknowledge your open task success.": "Acknowledge your open task success.",
    "missing 'Chat' field": "Please enter 'Chat' or 'Attahc file'.",
    "missing 'Order' field": "Please enter 'Order'.",
    "Add new announcement success.": "Add new announcement success.",
    "Notification": "Notification",
    "Master": "Master",
    "Super User": "Super User",
    "Lead": "Lead",
    "Normal": "Normal",
    "General": "General",
    "Chat Bot": "Chat Bot",
    "Dashboard": "Dashboard",
    "Task Tracking": "Task Tracking",
    "Askmebet": "Askmebet",
    "Casino": "Casino",
    "Football": "Football",
    "Ambbo": "Ambbo",
    "Prefix Detail": "Prefix Detail",
    "Report": "Report",
    "Report Conclude": "Report Conclude",
    "Promotion": "Promotion",
    "Check Balance": "Check Balance",
    "Management": "Management",
    "Company": "Company",
    "Agent": "Agent",
    "Sub Agent": "Sub Agent",
    "Account": "Account",
    "Leave": "Leave",
    "Announcement": "Announcement",
    "Add": "<i class='fas fa-plus mr-1'></i>Add",
    "Agent_": "Agent :",
    "Sub Agent_": "Sub Agent :",
    "Start date_": "Start date :",
    "To date_": "To date :",
    "Search": "Search",
    "No": "No",
    "Title": "Title",
    "Description": "Description",
    "Agent": "Agent",
    "Start Date": "Start Date",
    "To Date": "To Date",
    "Image": "Image",
    "No Data.": "No Data.",
    "Attach File": "Attach File",
    "Add Announcement": "Add Announcement",
    "Add Feedback": "Add Feedback",
    "Add new feedback success.": "Add new feedback success.",
    "Feedback": "Feedback",
    "Category": "Category",
    "Amount": "Amount",
    "New today": "New today",
    "New": "New",
    "Open": "Open",
    "Waiting": "Waiting",
    "Done": "Done",
    "Cancel": "Cancel",
    "Total": "Total",
    "Sport": "Sport",
    "Casino": "Casino",
    "Lotto": "Lotto",
    "Game": "Game",
    "sport": "Sport",
    "casino": "Casino",
    "lotto": "Lotto",
    "game": "Game",
    "Total case": "Total case :",
    "Title_": "Title :",
    "Description_": "Description :",
    "All": "All",
    "Search_": "Search :",
    "Category_": "Category :",
    "Status_": "Status :",
    "My task": "My task",
    "Product / Agent / Prefix": "Product / Agent / Prefix",
    "Create date": "Create date",
    "Create by": "Create by",
    "Add new sub agent success.": "Add new sub agent success.",
    "Add new feedback success.": "Add new feedback success.",
    "missing 'Message' field": "Please enter 'Message'.",
    "Create by": "Create by",
    "Manual ENG": "Manual ENG",
    "Manual TH": "Manual TH",
    "None": "-",
    "Sportbook": "Sportbook",
    "Slot": "Slot",
    "Poker": "Poker",
    "Add Company": "Add Company",
    "Add Agent": "Add Agent",
    "Add Sub Agent": "Add Sub Agent",
    "Add Account": "Add Account",
    "Add Leave": "Add Leave",
    "How to use": "How to use",
    "E-Book": "E-Book",
    "Video": "Video",
    "PDF": "PDF",
    "-": "-",
    "Note_ You can only upload a maximum of 5 files.": "Note: You can only upload a maximum of 5 files.",
    "Attach file_": "Attach file :",
    "Other_": "Other :",
    "Product_v": "<label style='color: red;'>*</label>Product :",
    "Agent / Prefix_v": "<label style='color: red;'>*</label>Agent / Prefix :",
    "Category_v": "<label style='color: red;'>*</label>Category :",
    "Level_v": "<label style='color: red;'>*</label>Level :",
    "Website link (Troubled)_v": "<label style='color: red;'>*</label>Website link (Troubled) :",
    "Username (Troubled)_v": "<label style='color: red;'>*</label>Username (Troubled) :",
    "Password (Troubled)_v": "<label style='color: red;'>*</label>Password (Troubled) :",
    "Problem_v": "<label style='color: red;'>*</label>Problem :",
    "Troubleshooting_v": "<label style='color: red;'>*</label>Troubleshooting :",
    "After first fixed_v": "<label style='color: red;'>*</label>After first fixed :",
    "Add Task Tracking": "Add Task Tracking",
    "Level": "Level",
    "Ticket ID": "Ticket ID",
    "Status": "Status",
    "Product": "Product",
    "Ag / Pref": "Ag / Pref",
    "Categories": "Categories",
    "Created date": "Created date",
    "Created by": "Created by",
    "Pick up / Action by": "Pick up / Action by",
    "Estimate end date": "Estimate end date",
    "Desc": "Desc",
    "Files": "Files",
    "Pick up": "Pick up",
    "Actions": "Actions",
    "Chat": "Chat",
    "Chat_": "Chat :",
    "Ticket ID_": "Ticket ID :",
    "Website link (Troubled)_": "Website link (Troubled) :",
    "Username (Troubled)_": "Username (Troubled) :",
    "Password (Troubled)_": "Password (Troubled) :",
    "Problem_": "Problem :",
    "Troubleshooting_": "Troubleshooting :",
    "After first fixed_": "After first fixed :",
    "Other_": "Other :",
    "Cann't delete this item because it is in use.": "Can't delete this item because it is in use.",
    "Name is duplicate.": "Name is duplicate.",
    "urgent": "urgent",
    "high": "high",
    "medium": "medium",
    "low": "low",
    "Select category": "Select category",
    "Select level": "Select level",
    "Profile": "Profile",
    "Title__": "<label style='color: red;'>*</label>Title :",
    "Message__": "<label style='color: red;'>*</label>Message :",
    "Description__": "<label style='color: red;'>*</label>Description :",
    "To Agent__": "<label style='color: red;'>*</label>To Agent :",
    "Start Date__": "<label style='color: red;'>*</label>Start Date :",
    "To Date__": "<label style='color: red;'>*</label>To Date :",
    "Order__": "<label style='color: red;'>*</label>Order :",
    "Select agent": "Select agent",
    "Leave type_": "Leave type :",
    "Total day": "Total day",
    "Approve by": "Approve by",
    "Approve date": "Approve date",
    "Leave date": "Leave date",
    "Confirm approve this leave ?": "Confirm approve this leave ?",
    "Confirm reject this leave ?": "Confirm reject this leave ?",
    "Select type": "Select type",
    "Type__": "<label style='color: red;'>*</label>Type :",
    "Remark_": "Remark :",
    "Name__": "<label style='color: red;'>*</label>Name :",
    "Prefix__": "<label style='color: red;'>*</label>Prefix :",
    "Company__": "<label style='color: red;'>*</label>Company :",
    "Name / Prefix": "Name / Prefix",
    "Name": "Name",
    "Prefix": "Prefix",
    "Remark": "Remark",
    "Edit Company": "Edit Company",
    "Select company": "Select company",
    "Company_": "Company :",
    "Edit Agent": "Edit Agent",
    "Agent__": "<label style='color: red;'>*</label>Agent :",
    "Delete Sub Agent": "Delete Sub Agent",
    "Edit Sub Agent": "Edit Sub Agent",
    "Select sub agent": "Select sub agent",
    "Username__": "<label style='color: red;'>*</label>Username :",
    "Password__": "<label style='color: red;'>*</label>Password :",
    "Contact_": "Contact :",
    "Level__": "<label style='color: red;'>*</label>Level :",
    "Level_": "Level :",
    "Edit Account": "Edit Account",
    "Contact": "Contact",
    "Login Time": "Login Time",
    "Username_": "Username :",
    "Save New Password": "Save New Password",
    "Old Password__": "<label style='color: red;'>*</label>Old Password :",
    "New Password__": "<label style='color: red;'>*</label>New Password :",
    "Confirm Password__": "<label style='color: red;'>*</label>Confirm Password :",
    "No Chat.": "No Chat.",
    "Bet ID_": "Bet ID :",
    "Please enter search.": "Please enter search.",
    "Bet ID": "Bet ID",
    "Before Credit": "Before Credit",
    "Game Type": "Game Type",
    "Game Date": "Game Date",
    "End Date": "End Date",
    "Production": "Production",
    "Bet Amount": "Bet Amount",
    "Game ID": "Game ID",
    "Detail": "Detail",
    "Tx ID": "Tx ID",
    "Source": "Source",
    "Game": "Game",
    "Prefix_": "Prefix :",
    "Company Name_": "Company Name :",
    "Product_": "Product :",
    "URL Old Data_": "URL Old Data :",
    "Logo_": "Logo :",
    "Agent ID_": "Agent ID :",
    "Line_": "Line :",
    "URL_": "URL :",
    "URL API_": "URL API :",
    "Background_": "Background :",
    "Promotion Name": "Promotion Name",
    "Type": "Type",
    "Min Topup": "Min Topup",
    "Max Topup": "Max Topup",
    "Max Bonus": "Max Bonus",
    "Turnover": "Turnover",
    "Max Withdraw": "Max Withdraw",
    "Type_": "Type :",
    "First topup": "First topup",
    "Decimal": "Decimal",
    "Withdraw Marketing": "Withdraw Marketing",
    "Affiliate": "Affiliate",
    "Report Deposit": "Report Deposit",
    "Withdraw": "Withdraw",
    "Deposit": "Deposit",
    "Wallet": "Wallet",
    "Truemoney": "Truemoney",
    "7 Day": "7 Day",
    "Problem": "Problem",
    "Cashback": "Cashback",
    "Amount_": "Amount :",
    "Datetime": "Datetime",
    "Name - Surname": "Name - Surname",
    "Topup": "Topup",
    "Bonus": "Bonus",
    "Recommend": "Recommend",
    "Bank Name": "Bank Name",
    "Summary": "Summary",
    "Summary Bonus": "Summary Bonus",
    "Action By": "Action By",
    "Update date": "Update date",
    "Date Bank": "Date Bank",
    "Credit after topup": "Credit after topup",
    "Value": "Value",
    "Credit before topup": "Credit before topup",
    "Balance before withdraw": "Balance before withdraw",
    "Fee": "Fee",
    "Balance after withdraw": "Balance after withdraw",
    "Count": "Count",
    "Account set": "Account set",
    "Withdrawal Date": "Withdrawal Date",
    "Name_": "Name :",
    "Wallet Main_": "Wallet Main :",
    "Wallet Win Lose_": "Wallet Win Lose :",
    "Shareholder Line_": "Shareholder Line :",
    "Wallet Transfer_": "Wallet Transfer :",
    "Wallet Commission_": "Wallet Commission :",
    "Balance": "Balance",
    "User": "User",
    "Promotion": "Promotion",
    "Hide": "Hide",
    "Count Deposit": "Count Deposit",
    "Sum Deposit": "Sum Deposit",
    "Count Withdraw": "Count Withdraw",
    "Sum Withdraw": "Sum Withdraw",
    "Sum Read Withdraw": "Sum Read Withdraw",
    "Topup + Bonus": "Topup + Bonus",
    "Profit Lost": "Profit Lost",
    "Profit Lost + Company": "Profit Lost + Company",
    "Channel Transfer": "Channel Transfer",
    "Company List": "Company List",
    "Agent List": "Agent List",
    "Sub Agent List": "Sub Agent List",
    "Account List": "Account List",
    "Estimate end date__": "<label style='color: red;'>*</label>Estimate end date :",
    "Confirm close task tracking ?": "Confirm close task tracking ?",
    "Confirm cancel task tracking ?": "Confirm cancel task tracking ?",
    "Previous": "Previous",
    "Yesterday": "Yesterday",
    "This week": "This week",
    "Last week": "Last week",
    "This month": "This month",
    "Last month": "Last month",
    "Next": "Next",
    "Today": "Today",
    "Multiplayer": "Multiplayer",
    "Delete announcement success.": "Delete announcement success.",
    "Edit announcement success.": "Edit announcement success.",
    "Delete Announcement": "Delete Announcement",
    "Username (Troubled)": "Username (Troubled)",
    "Edit Announcement": "Edit Announcement",
    "Field 'Username' should be at least 2 characters.": "Field 'Username' should be at least 2 characters.",
    "Delete File": "Delete File",
    "Delete file success.": "Delete file success.",
    "Confirm unsend chat ?": "Confirm unsend chat ?",
    "Unsend chat success.": "Unsend chat success.",
    "Delete file.": "Delete file.",
    "Unsend Chat": "Unsend Chat",
    "Add Sub Account": "Add Sub Account",
    "Sub Account List": "Sub Account List",
    "Vpay": "VPay",
    "Add new sub account success.": "Add new sub account success.",
    "Edit sub account success.": "Edit sub account success.",
    "Delete sub account success.": "Delete sub account success.",
    "Announcement Line": "Announcement Line",
    "Send Announcement Line": "Send Announcement Line",
    "Add Announcement Line": "Add announce Line",
    "Send announcement line success.": "Send announcement line success.",
    "Confirm": "Confirm",
    "Confirm send announcement to line?": "Confirm send announcement to line?",
    "Line Token": "Line Token",
    "Name Group": "Name Group",
    "Token": "Token",
    "Add Line Token": "Add Line Token",
    "Edit Line Token": "Edit Line Token",
    "Name group is duplicate.": "Name group is duplicate.",
    "Edit line token success.": "Edit line token success.",
    "Delete line token success.": "Delete line token success.",
    "Delete Line Token": "Delete Line Token",
    "missing 'Name group' field": "Please enter 'Name group'",
    "missing 'Token' field": "Please enter 'Token'",
    "Add new line token success.": "Add new line token success.",
    "NameGroup__": "<label style='color: red;'>*</label>Name group :",
    "Token__": "<label style='color: red;'>*</label>Token :",
};

var Thai = {
    "Emergency": "ฉุกเฉิน",
    "Mobile Version": "<i class='fas fa-mobile'></i>&nbsp;เวอร์ชั่นมือถือ",
    "Askmebet Support": "Askmebet Support",
    "Username": "ชื่อผู้ใช้งาน",
    "Password": "รหัสผ่าน",
    "Sign in": "เข้าสู่ระบบ",
    "Contact your associate in case you forgot the password or unable to sign in": "ติดต่อตัวแทนของคุณในกรณีที่คุณลืมรหัสผ่านหรือไม่สามารถลงชื่อเข้าใช้ได้",
    "Close": "ปิด",
    "Guide": "<i class='fas fa-guide'></i>&nbsp;คู่มือใช้งาน",
    "Log Out": "<i class='fas fa-sign-out-alt'></i>&nbsp;ออกจากระบบ",
    "Chat Bot": "แชทบอท",
    "Search User": "ค้นหาผู้ใช้งาน",
    "Pretty Gaming": "Pretty Gaming",
    "Super Slot": "Super Slot",
    "Football": "ฟุตบอล",
    "Lotto": "ล็อตโต้",
    "Ambbet": "Ambbet",
    "missing 'Title' field": "กรุณากรอก 'เรื่อง'",
    "missing 'Comment' field": "กรุณากรอก 'คอมเม้น'",
    "missing 'Username' field": "กรุณากรอก 'ชื่อผู้ใช้งาน'",
    "missing 'Password' field": "กรุณากรอก 'รหัสผ่าน'",
    "missing 'Contact' field": "กรุณากรอก 'ติดต่อ'",
    "missing 'Level' field": "กรุณาเลือก 'ระดับ'",
    "missing 'Company' field": "กรุณาเลือก 'บริษัท'",
    "missing 'Sub Agent' field": "กรุณาเลือก'เอเย่นต์ย่อย'",
    "Save": "บันทึก",
    "Add new account success.": "เพิ่มบัญชีผู้ใช้ใหม่สำเร็จ",
    "Add new sub account success.": "เพิ่มบัญชีย่อยใหม่สำเร็จ.",
    "Data recording failed.": "การบันทึกข้อมูลล้มเหลว กรุณาลองใหม่อีกครั้ง",
    "Username is duplicate.": "ชื่อผู้ใช้นี้มีอยู่แล้ว",
    "Delete Account": "ลบบัญชีผู้ใช้",
    "Confirm delete this item ?": "ยืนยันลบรายการนี้หรือไม่ ?",
    "OK": "ตกลง",
    "Delete account success.": "ลบบัญชีผู้ใช้สำเร็จ",
    "Delete sub account success.": "ลบบัญชีย่อยสำเร็จ",
    "Edit account success.": "แก้ไขบัญชีผู้ใช้สำเร็จ",
    "Edit sub account success.": "แก้ไขบัญชีย่อยสำเร็จ",
    "missing 'Name' field": "กรุณากรอก 'ชื่อ'",
    "missing 'Prefix' field": "กรุณากรอก 'ชื่อย่อ'",
    "Login failed.": "เข้าสู่ระบบล้มเหลว กรุณาลองใหม่อีกครั้ง",
    "Logout failed.": "ออกจากระบบล้มเหลว กรุณาลองใหม่อีกครั้ง",
    "Please select type.": "กรุณาเลือกประเภท",
    "Please select agent.": "กรุณาเลือกเอเย่นต์",
    "Please enter bet ID.": "กรุณากรอกรหัสเดิมพัน",
    "Cancel bet ID success.": "ยกเลิกรหัสเดิมพันสำเร็จ",
    "Add new dashboard success.": "เพิ่มแดชบอร์ดใหม่สำเร็จ",
    "missing 'Product' field": "กรุณากรอก 'ผลิตภัณฑ์'",
    "missing 'Agent' field": "กรุณากรอก 'เอเย่นต์'",
    "missing 'Attach file' field": "กรุณาเลือก 'ไฟล์แนบ'",
    "missing 'Category' field": "กรุณาเลือก 'หมวดหมู่'",
    "missing 'Status' field": "กรุณาเลือก 'สถานะ'",
    "missing 'Start date' field": "กรุณากรอก 'วันที่เริ่มต้น'",
    "missing 'To date' field": "กรุณากรอก 'วันที่สิ้นสุด'",
    "missing 'Type' field": "กรุณาเลือก 'ประเภท'",
    "missing 'Description' field": "กรุณากรอก 'คำอธิบาย'",
    "Add new leave success.": "เพิ่มการลาใหม่สำเร็จ",
    "Approve this leave success.": "อนุมัติรายการลานี้สำเร็จ",
    "Reject this leave success.": "ไม่อนุมัติรายการลานี้สำเร็จ",
    "missing 'Search' field": "กรุณากรอก 'รหัสเดิมพัน' หรือ 'ชื่อผู้ใช้งาน'",
    "missing 'Old Password' field": "กรุณากรอก 'รหัสผ่านเก่า'",
    "missing 'New Password' field": "กรุณากรอก 'รหัสผ่านใหม่'",
    "missing 'Confirm Password' field": "กรุณากรอก 'ยืนยันรหัสผ่าน'",
    "New password doesn't match confirm password": "รหัสผ่านใหม่ไม่ตรงกับรหัสผ่านยืนยัน",
    "Pickup dashboard success.": "รับเคสแดชบอร์ดสำเร็จ",
    "Chat dashboard success.": "แชทเคสแดชบอร์ดสำเร็จ",
    "Comment dashboard success.": "คอมเม้นเคสแดชบอร์ดสำเร็จ",
    "Close dashboard success.": "ปิดเคสแดชบอร์ดสำเร็จ",
    "Cancel dashboard success.": "ยกเลิกเคสแดชบอร์ดสำเร็จ",
    "Data recording failed. (Upload attach file)": "การบันทึกข้อมูลล้มเหลว กรุณาลองใหม่อีกครั้ง (อัปโหลดไฟล์แนบ)",
    "The old password doesn't match the current password.": "รหัสผ่านเก่าไม่ตรงกับรหัสผ่านปัจจุบัน",
    "Password must be greater than 8 characters.": "รหัสผ่านต้องมีความยาว 8 ตัวอักษรขึ้นไป",
    "Field 'To Date' should be greater than 'Start Date'.": "ฟิลด์ 'วันที่สิ้นสุด' ควรมากกว่า 'วันที่เริ่มต้น'",
    "missing 'Website' field": "กรุณากรอก 'ลิงค์เว็บไซต์'",
    "missing 'Username' field": "กรุณากรอก 'ชื่อผู้ใช้งาน'",
    "missing 'Password' field": "กรุณากรอก 'รหัสผ่าน'",
    "missing 'Problem' field": "กรุณากรอก 'ปัญหา'",
    "missing 'Troubleshooting' field": "กรุณากรอก 'การแก้ไขปัญหา'",
    "missing 'Afterfirstfixed' field": "กรุณากรอก 'หลังจากแก้ไขครั้งแรก'",
    "Add new company success.": "เพิ่มบริษัทใหม่สำเร็จ",
    "Delete Company": "ลบบริษัท",
    "Delete company success.": "ลบบริษัทสำเร็จ",
    "Edit company success.": "แก้ไขบริษัทสำเร็จ",
    "Add new agent success.": "เพิ่มเอเย่นต์ใหม่สำเร็จ",
    "Delete Agent": "ลบเอเย่นต์",
    "Delete agent success.": "ลบเอเยย่นต์สำเร็จ",
    "Edit agent success.": "แก้ไขเอเย่นต์สำเร็จ",
    "Delete sub agent success.": "ลบเอเย่นต์ย่อยสำเร็จ",
    "Edit sub agent success.": "แก้ไขเอเย่นต์ย่อยสำเร็จ",
    "Acknowledge your open task success.": "รับทราบสถานะงานที่คุณเปิดสำเร็จ",
    "missing 'Chat' field": "กรุณากรอก 'แชท' หรือ 'ไฟล์แนบ'",
    "missing 'Order' field": "กรุณากรอก 'ลำดับ'",
    "Add new announcement success.": "เพิ่มประกาศใหม่สำเร็จ",
    "Notification": "การแจ้งเตือน",
    "Master": "มาสเตอร์",
    "Super User": "ซุปเปอร์ยูสเซอร์",
    "Lead": "หัวหน้า",
    "Normal": "ปกติ",
    "General": "ทั่วไป",
    "Chat Bot": "แชทบอท",
    "Dashboard": "แดชบอร์ด",
    "Task Tracking": "การติดตามงาน",
    "Askmebet": "Askmebet",
    "Casino": "คาสิโน",
    "Football": "ฟุตบอล",
    "Ambbo": "Ambbo",
    "Prefix Detail": "รายละเอียดชื่อย่อ",
    "Report": "รายงาน",
    "Report Conclude": "รายงานสรุป",
    "Promotion": "โปรโมชั่น",
    "Check Balance": "ตรวจสอบยอดเงิน",
    "Management": "การจัดการ",
    "Company": "บริษัท",
    "Agent": "เอเย่นต์",
    "Sub Agent": "เอเย่นต์ย่อย",
    "Account": "บัญชีผู้ใช้",
    "Leave": "การลา",
    "Announcement": "การประกาศ",
    "Add": "<i class='fas fa-plus mr-1'></i>เพิ่ม",
    "Agent_": "เอเย่นต์ :",
    "Sub Agent_": "เอเย่นต์ย่อย :",
    "Start date_": "วันที่เริ่มต้น :",
    "To date_": "วันที่สิ้นสุด :",
    "Search": "ค้นหา",
    "No": "ลำดับ",
    "Title": "เรื่อง",
    "Description": "คำอธิบาย",
    "Agent": "เอเย่นต์",
    "Start Date": "วันที่เริ่มต้น",
    "To Date": "วันที่สิ้นสุด",
    "Image": "รูปภาพ",
    "No Data.": "ไม่มีข้อมูล",
    "Attach File": "ไฟล์แนบ",
    "Add Announcement": "เพิ่มการประกาศ",
    "Add Feedback": "เพิ่มข้อเสนอแนะ",
    "Add new feedback success.": "เพิ่มข้อเสนอแนะใหม่สำเร็จ",
    "Feedback": "ข้อเสนอแนะ",
    "Category": "หมวดหมู่",
    "Amount": "จำนวน",
    "New today": "ใหม่วันนี้",
    "New": "ใหม่",
    "Open": "เปิด",
    "Waiting": "กำลังรอ",
    "Done": "เสร็จสิ้น",
    "Cancel": "ยกเลิก",
    "Total": "รวม",
    "Sport": "กีฬา",
    "Casino": "คาสิโน",
    "Lotto": "ล็อตโต้",
    "Game": "เกมส์",
    "sport": "กีฬา",
    "casino": "คาสิโน",
    "lotto": "ล็อตโต้",
    "game": "เกมส์",
    "Total case": "รวมเคส :",
    "Title_": "เรื่อง :",
    "Description_": "คำอธิบาย :",
    "All": "ทั้งหมด",
    "Search_": "ค้นหา :",
    "Category_": "หมวดหมู่ :",
    "Status_": "สถานะ :",
    "My task": "งานของฉัน",
    "Product / Agent / Prefix": "ผลิตภัณฑ์ / เอเย่นต์ / ชื่อย่อ",
    "Create date": "วันที่สร้าง",
    "Create by": "สร้างโดย",
    "Add new sub agent success.": "เพิ่มเอเย่นต์ย่อยใหม่สำเร็จ",
    "Add new feedback success.": "เพิ่มข้อเสนอแนะใหม่สำเร็จ",
    "missing 'Message' field": "กรุณากรอก 'ข้อความ'",
    "Create by": "สร้างโดย",
    "Manual ENG": "คู่มือภาษาอังกฤษ",
    "Manual TH": "คู่มือภาษาไทย",
    "None": "-",
    "Sportbook": "Sportbook",
    "Slot": "สล็อต",
    "Poker": "โป๊กเกอร์",
    "Add Company": "เพิ่มบริษัท",
    "Add Agent": "เพิ่มเอเย่นต์",
    "Add Sub Agent": "เพิ่มเอเย่นต์ย่อย",
    "Add Account": "เพิ่มบัญชีผู้ใช้",
    "Add Leave": "เพิ่มการลา",
    "How to use": "วิธีใช้",
    "E-Book": "E-Book",
    "Video": "วิดีโอ",
    "PDF": "PDF",
    "-": "-",
    "Note_ You can only upload a maximum of 5 files.": "หมายเหตุ: คุณสามารถอัปโหลดไฟล์ได้สูงสุด 5 ไฟล์",
    "Attach file_": "ไฟล์แนบ :",
    "Other_": "อื่นๆ :",
    "Product_v": "<label style='color: red;'>*</label>ผลิตภัณฑ์ :",
    "Agent / Prefix_v": "<label style='color: red;'>*</label>เอเย่นต์ / ชื่อย่อ :",
    "Category_v": "<label style='color: red;'>*</label>หมวดหมู่ :",
    "Level_v": "<label style='color: red;'>*</label>ระดับ :",
    "Website link (Troubled)_v": "<label style='color: red;'>*</label>ลิงค์เว็บไซต์ (ที่มีปัญหา) :",
    "Username (Troubled)_v": "<label style='color: red;'>*</label>ชื่อผู้ใช้งาน (ที่มีปัญหา) :",
    "Password (Troubled)_v": "<label style='color: red;'>*</label>รหัสผ่าน (ที่มีปัญหา) :",
    "Problem_v": "<label style='color: red;'>*</label>ปัญหา :",
    "Troubleshooting_v": "<label style='color: red;'>*</label>การแก้ไขปัญหา :",
    "After first fixed_v": "<label style='color: red;'>*</label>หลังจากแก้ไขครั้งแรก :",
    "Add Task Tracking": "เพิ่มการติดตามงาน",
    "Level": "ระดับ",
    "Ticket ID": "รหัสตั๋ว",
    "Status": "สถานะ",
    "Product": "ผลิตภัณฑ์",
    "Ag / Pref": "เอเย่นต์ / ชื่อย่อ",
    "Categories": "หมวดหมู่",
    "Created date": "วันที่สร้าง",
    "Created by": "สร้างโดย",
    "Pick up / Action by": "รับเคส / ทำโดย",
    "Estimate end date": "วันที่สิ้นสุดประมาณ",
    "Desc": "อธิบาย",
    "Files": "ไฟล์",
    "Pick up": "รับเคส",
    "Actions": "ดำเนินการ",
    "Chat": "แชท",
    "Chat_": "แชท :",
    "Ticket ID_": "รหัสตั๋ว :",
    "Website link (Troubled)_": "ลิงค์เว็บไซต์ (ที่มีปัญหา) :",
    "Username (Troubled)_": "ชื่อผู้ใช้งาน (ที่มีปัญหา) :",
    "Password (Troubled)_": "รหัสผ่าน (ที่มีปัญหา) :",
    "Problem_": "ปัญหา :",
    "Troubleshooting_": "การแก้ไขปัญหา :",
    "After first fixed_": "หลังจากแก้ไขครั้งแรก :",
    "Other_": "อื่นๆ :",
    "Cann't delete this item because it is in use.": "ไม่สามารถลบรายการนี้ได้ เนื่องจากมีการใช้งานอยู่",
    "Name is duplicate.": "ชื่อนี้มีอยู่แล้ว",
    "urgent": "ด่วน",
    "high": "สูง",
    "medium": "ปานกลาง",
    "low": "ต่ำ",
    "Select category": "เลือกหมวดหมู่",
    "Select level": "เลือกระดับ",
    "Profile": "โปรไฟล์",
    "Title__": "<label style='color: red;'>*</label>เรื่อง :",
    "Message__": "<label style='color: red;'>*</label>ข้อความ :",
    "Description__": "<label style='color: red;'>*</label>คำอธิบาย :",
    "To Agent__": "<label style='color: red;'>*</label>ถึงเอเย่นต์ :",
    "Start Date__": "<label style='color: red;'>*</label>วันที่เริ่มต้น :",
    "To Date__": "<label style='color: red;'>*</label>วันที่สิ้นสุด :",
    "Order__": "<label style='color: red;'>*</label>ลำดับที่ :",
    "Select agent": "เลือกเอเย่นต์",
    "Leave type_": "ประเภทการลา :",
    "Total day": "รวมวัน",
    "Approve by": "อนุมัติโดย",
    "Approve date": "อนุมัติวันที่",
    "Leave date": "วันที่ลา",
    "Confirm approve this leave ?": "ยืนยันอนุมัติการลานี้หรือไม่ ?",
    "Confirm reject this leave ?": "ยืนยันไม่อนุมัติการลานี้หรือไม่ ?",
    "Select type": "เลือกประเภท",
    "Type__": "<label style='color: red;'>*</label>ประเภท :",
    "Remark_": "หมายเหตุ :",
    "Name__": "<label style='color: red;'>*</label>ชื่อ :",
    "Prefix__": "<label style='color: red;'>*</label>ชื่อย่อ :",
    "Company__": "<label style='color: red;'>*</label>บริษัท :",
    "Name / Prefix": "ชื่อ / ชื่อย่อ",
    "Name": "ชื่อ",
    "Prefix": "ชื่อย่อ",
    "Remark": "หมายเหตุ",
    "Edit Company": "แก้ไขบริษัท",
    "Select company": "เลือกบริษัท",
    "Company_": "บริษัท :",
    "Edit Agent": "แก้ไขเอเย่นต์",
    "Agent__": "<label style='color: red;'>*</label>เอเย่นต์ :",
    "Delete Sub Agent": "ลบเอเย่นต์",
    "Edit Sub Agent": "แก้ไขเอเย่นต์ย่อย",
    "Select sub agent": "เลือกเอเย่นต์ย่อย",
    "Username__": "<label style='color: red;'>*</label>ชื่อผู้ใช้งาน :",
    "Password__": "<label style='color: red;'>*</label>รหัสผ่าน :",
    "Contact_": "ติดต่อ :",
    "Level__": "<label style='color: red;'>*</label>ระดับ :",
    "Level_": "ระดับ :",
    "Edit Account": "แก้ไขบัญชีผู้ใช้",
    "Contact": "ติดต่อ",
    "Login Time": "เวลาเข้าสู่ระบบ",
    "Username_": "ชื่อเข้าใช้งาน :",
    "Save New Password": "บันทึกรหัสผ่านใหม่",
    "Old Password__": "<label style='color: red;'>*</label>รหัสผ่านเก่า :",
    "New Password__": "<label style='color: red;'>*</label>รหัสผ่านใหม่ :",
    "Confirm Password__": "<label style='color: red;'>*</label>ยืนยันรหัสผ่าน :",
    "No Chat.": "ไม่มีแชท",
    "Bet ID_": "รหัสเดิมพัน :",
    "Please enter search.": "โปรดป้อนการค้นหา",
    "Bet ID": "รหัสเดิมพัน",
    "Before Credit": "เครดิตก่อน",
    "Game Type": "ประเภทเกมส์",
    "Game Date": "เกมส์วันที่",
    "End Date": "วันที่สิ้นสุด",
    "Production": "ผลิตภัณฑ์",
    "Bet Amount": "จำนวนเงินเดิมพัน",
    "Game ID": "รหัสเกมส์",
    "Detail": "รายละเอียด",
    "Tx ID": "Tx ID",
    "Source": "ที่มา",
    "Game": "เกมส์",
    "Prefix_": "ชื่อย่อ :",
    "Company Name_": "ชื่อบริษัท :",
    "Product_": "ผลิตภัณฑ์ :",
    "URL Old Data_": "URL Old Data :",
    "Logo_": "โลโก้ :",
    "Agent ID_": "รหัสเอเย่นต์ :",
    "Line_": "ไลน์ :",
    "URL_": "URL :",
    "URL API_": "URL API :",
    "Background_": "ภาพพื้นหลัง :",
    "Promotion Name": "ชื่อโปรโมชั่น",
    "Type": "ประเภท",
    "Min Topup": "ฝากต่ำสุด",
    "Max Topup": "ฝากสูงสุด",
    "Max Bonus": "โบนัสสูงสุด",
    "Turnover": "ยอดเทิร์น",
    "Max Withdraw": "ถอนสูงสุด",
    "Type_": "ประเภท :",
    "First topup": "ฝากครั้งแรก",
    "Decimal": "ฝากทศนิยม",
    "Withdraw Marketing": "ราการถอนค่าแนะนำ",
    "Affiliate": "เช็ครายการ AFFILIATE",
    "Report Deposit": "รายการฝาก",
    "Withdraw": "รายการถอนเงิน",
    "Deposit": "เงินฝาก",
    "Wallet": "ย้ายจากวอเรท",
    "Truemoney": "ทรูมันนี่",
    "7 Day": "ฝาก 7 วัน",
    "Problem": "ผิดพลาดต่างๆ",
    "Cashback": "เครดิตเงินคืนทั่วไป",
    "Amount_": "จำนวน :",
    "Datetime": "วันที่",
    "Name - Surname": "ชื่อ - นามสกุล",
    "Topup": "เติม",
    "Bonus": "โบนัส",
    "Recommend": "แนะนำมาจาก",
    "Bank Name": "ชื่อธนาคาร",
    "Summary": "รวม",
    "Summary Bonus": "รวมโบนัส",
    "Action By": "ทำโดย",
    "Update date": "วันที่อัพเดต",
    "Date Bank": "วันที่ธนาคาร",
    "Credit after topup": "เครดิตหลังเติมเงิน",
    "Value": "จำนวน",
    "Credit before topup": "เครดิตก่อนเติมเงิน",
    "Balance before withdraw": "ยอดก่อนถอน",
    "Fee": "ค่าธรรมเนียม",
    "Balance after withdraw": "ยอดหลังถอน",
    "Count": "จำนวน",
    "Account set": "ชุดบัญชี",
    "Withdrawal Date": "วันที่ถอน",
    "Name_": "ชื่อ :",
    "Wallet Main_": "กระเป๋าเงินหลัก :",
    "Wallet Win Lose_": "กระเป๋าแพ้ชนะ :",
    "Shareholder Line_": "สายผู้ถือหุ้น :",
    "Wallet Transfer_": "การโอนกระเป๋าเงิน :",
    "Wallet Commission_": "ค่าคอมมิชชั่นกระเป๋า :",
    "Balance": "รายงานกำไรขาดทุน",
    "User": "รายงานการฝาก/ถอนตามบุคคล",
    "Promotion": "รายการสรุปโปรโมชั่น",
    "Hide": " รายการที่ถูกซ่อน",
    "Count Deposit": "จำนวนเงินฝาก",
    "Sum Deposit": "รวมเงินฝาก",
    "Count Withdraw": "จพนวนถอน",
    "Sum Withdraw": "รวมถอน",
    "Sum Read Withdraw": "Sum Read Withdraw",
    "Topup + Bonus": "เติมเงิน + โบนัส",
    "Profit Lost": "กำไรขาดทุน",
    "Profit Lost + Company": "กำไรขาดทุน + บริษัท",
    "Channel Transfer": "ช่องทางการโอน",
    "Company List": "รายชื่อบริษัท",
    "Agent List": "รายชื่อเอเย่นต์",
    "Sub Agent List": "รายชื่อเอเย่นต์ย่อย",
    "Account List": "รายชื่อบัญชีผู้ใช้",
    "Estimate end date__": "<label style='color: red;'>*</label>วันที่สิ้นสุดประมาณ :",
    "Confirm close task tracking ?": "ยืนยันปิดเคสหรือไม่ ?",
    "Confirm cancel task tracking ?": "ยืนยันยกเลิกเคสหรือไม่ ?",
    "Previous": "ก่อนหน้า",
    "Yesterday": "เมื่อวานนี้",
    "This week": "สัปดาห์นี้",
    "Last week": "สัปดาห์ที่แล้ว",
    "This month": "เดือนนี้",
    "Last month": "เดือนที่แล้ว",
    "Next": "ถัดไป",
    "Today": "วันนี้",
    "Multiplayer": "มัลติเพลเยอร์",
    "Delete announcement success.": "ลบการประกาศสำเร็จ",
    "Edit announcement success.": "แก้ไขการประกาศสำเร็จ",
    "Delete Announcement": "ลบการประกาศ",
    "Username (Troubled)": "ชื่อผู้ใช้งาน (ที่มีปัญหา)",
    "Edit Announcement": "แก้ไขการประกาศ",
    "Field 'Username' should be at least 2 characters.": "ฟิลด์ 'ชื่อผู้ใช้งาน' ควรมีอย่างน้อย 2 ตัวอักษรขึ้นไป",
    "Delete File": "ลบไฟล์",
    "Delete file success.": "ลบไฟล์สำเร็จ",
    "Confirm unsend chat ?": "ยืนยันลบแชท ?",
    "Unsend chat success.": "ยกเลิกการส่งแชทสำเร็จ",
    "Delete file.": "ลบไฟล์",
    "Unsend Chat": "ยกเลิกแชท",
    "Add Sub Account": "เพิ่มบัญชีย่อย",
    "Sub Account List": "รายชื่อบัญชีย่อย",
    "Vpay": "วีเปย์",
    "Announcement Line": "การประกาศทางไลน์",
    "Send Announcement Line": "ส่งประกาศทางไลน์",
    "Add Announcement Line": "เพิ่มประกาศทางไลน์",
    "Send announcement line success.": "ส่งประกาศทางไลน์สำเร็จ",
    "Confirm": "ยืนยัน",
    "Confirm send announcement to line?": "ยืนยันการส่งประกาศทางไลน์?",
    "Line Token": "ไลน์โทเค็น",
    "Name Group": "ชื่อกลุ่ม",
    "Token": "โทเค็น",
    "Add Line Token": "เพิ่มไลน์โทเค็น",
    "Edit Line Token": "แก้ไขไลน์โทเค็น",
    "Delete Line Token": "ลบไลน์โทเค็น",
    "Name group is duplicate.": "ชื่อกลุ่มนี้มีอยู่แล้ว",
    "Edit line token success.": "แก้ไขไลน์โทเค็นสำเร็จ",
    "Delete line token success.": "ลบไลน์โทเค็นสำเร็จ",
    "missing 'Name group' field": "กรุณากรอก 'ชื่อกลุ่ม'",
    "missing 'Token' field": "กรุณากรอก 'โทเค็น'",
    "Add new line token success.": "เพิ่มไลน์โทเค็นใหม่สำเร็จ",
    "NameGroup__": "<label style='color: red;'>*</label>ชื่อกลุ่ม :",
    "Token__": "<label style='color: red;'>*</label>โทเค็น :",
}

var Chinese = {

};


